[connection]
ip_address = "192.168.1.7"
port = 502

[[params]]
param_id = 1
slave_id = 1
start_address = 0
data_type = 3
operation = 2
register_type = 2
name = "电流"
unit = "A"

[[params]]
param_id = 2
slave_id = 1
start_address = 2
data_type = 3
operation = 2
register_type = 2
name = "电压"
unit = "V"

[[params]]
param_id = 3
slave_id = 1
start_address = 4
data_type = 1
operation = 2
register_type = 2
name = "温度"
unit = "℃"
